### ISSUE TITLE
Enable greenkeeper

### ISSUE THREAD

**Issue by diasdavid** [whyrusleeping/js-mafmt#10]
@whyrusleeping could you do

```
# clone the repo and go into its folder
> npm i -g greenkeeper
> greenkeeper enable
```

Thank you :)

**Comment by whyrusleeping** [comment]
Can you do this one? It wants me to give greenkeeper github permissions, which i'm not really on board with.

**Comment by diasdavid** [comment]
I see, should be just read, no? I can't, since you are the owner of the repo.

**Comment by dignifiedquire** [comment]
@whyrusleeping you can make @diasdavid or me "admin" then we can do it

**Comment by diasdavid** [comment]
@whyrusleeping would have to transfer the repo to us. Another option is moving it to ipfs and reuse the already given permissions.

**Comment by dignifiedquire** [comment]
shouldn't this be part of `multiformats` org anyway?

**Comment by whyrusleeping** [comment]
Can i close this? i really don't enjoy greenkeeper in the first place...
