### ISSUE TITLE
publish without the `js-` prefix

### ISSUE THREAD

**Issue by diasdavid** [whyrusleeping/js-mafmt#3]
@whyrusleeping could you publish the module without the [`js-` prefix](https://github.com/whyrusleeping/js-mafmt/blob/master/package.json#L2)? We've been creating the repos with it so it is easy to skim through on github and see which ones are the js or go implementations, but when publishing to the npm-land, we only keep the name of the module.

You will have to unpublish first (to avoid leftovers)
```sh
> npm unpublish -f
# change the name
> npm publish
```

**Comment by whyrusleeping** [comment]
I'll do this after #2 merges

**Comment by dignifiedquire** [comment]
This is done
